name: secret
on: push
env:
  ARTIFACT_NAME: myArtifact
  ARTIFACT_DOWNLOAD_NAME: myArtifactDownloaded
jobs:
  main:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: ${{env.ARTIFACT_NAME}}
         path: .
  child:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./downloaded
     
     
     
